version: '3'
services:
  #? [additional] if you want to use postgres internally in the docker-compose
  # redis:
  #   container_name: redis
  #   restart: always
  #   image: redis:6-alpine
  #   env_file:
  #     - ./.env.ci
  #   ports:
  #     - '6380:6380'
  #   volumes:
  #     - .:/redis
  #? [additional] if you want to use postgres internally in the docker-compose
  identity-db:
    container_name: identity-db
    image: postgres:latest
    restart: unless-stopped
    networks:
      - identity
    env_file:
      - ./.env.ci
    expose:
      - 5433
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=5433
    volumes:
      - ./data:/var/lib/postgresql/data
    command:
      - -p 5433
    ports:
      - 5433:5433
  digivite-identity:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    #? you can use network_mode instead if you want to use the host network
    # network_mode: "host"
    networks:
      - identity
    env_file:
      - ./.env.ci
    ports:
      - 4000:4000
    depends_on:
      # - redis
      - identity-db
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
volumes:
  data:
  node_modules:
  # redis:
networks:
  identity:
    driver: bridge
